rvm:
    - "2.0.0"
script: "bundle exec rake spec && bundle exec rake cucumber"
addons:
  postgresql: "9.3"

before_script:
  - psql -c "create database stowaway_test;" -U postgres

notifications:
  webhooks:
    - https://infinitedigitalnow.slack.com/services/hooks/travis?token=9YDDTGeOtgTqImEeDmERGzhc


