# This file can be renamed to application.yml. application.yml
# should never be checked into git.
# Add application configuration variables here, as shown below.
#
# MANDRILL_API_KEY: 12345
# ADMIN_NAME: Storage Admin
# ADMIN_EMAIL: admin@stowaway.co
# ADMIN_PASSWORD: somepassword
# FACEBOOK_APP_ID: 
# FACEBOOK_APP_SECRET: 
# AWS_ACCESS_KEY_ID: 
# AWS_SECRET_ACCESS_KEY: 
# AWS_REGION: 'us-east-1'
# STRIPE_SK: 
# STRIPE_PK: 
# GETSENTRY_KEY:
# CUSTOMERIO_API_KEY:
