---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-10.04.box
  run_list:
  - recipe[apt]
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
  run_list:
  - recipe[yum::epel]
- name: centos-5.8
  driver_config:
    box: opscode-centos-5.8
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-5.8.box
  run_list:
  - recipe[yum::epel]
suites:
- name: sentinel
  run_list:
    - "recipe[redis::sentinel]"
  attributes:
    redis:
      install_type: source
- name: replication
  run_list:
    - "recipe[redis::data_bag]"
  attributes:
    redis:
      instances:
      - "memory"
      - "persistant"
      - "sentinel"
- name: data_bag
  run_list:
    - "recipe[redis::data_bag]"
  attributes:
    redis:
      instances:
      - "memory_slave"
      - "persistant"
- name: package
  run_list:
    - "recipe[redis::server]"
- name: source
  run_list:
    - "recipe[redis::server]"
  attributes:
    redis:
      install_type: source
      config:
        logfile: /var/log/redis/server.log
- name: slaveof
  run_list:
    - "recipe[redis::server]"
  attributes:
    redis:
      install_type: source
      config:
        logfile: /var/log/redis/server.log
        slaveof_ip: 198.18.0.1
        slaveof_port: 3000
